### ISSUE TITLE
Add dependabot config

### ISSUE THREAD

**Issue by mpminardi** [adopted-ember-addons/torii#11]
Noticed that [dependabot](https://docs.github.com/en/code-security/dependabot) does not seem to be set up but was at some point in the base repo going off of the pull requests [currently open there](https://github.com/Vestorly/torii/pulls). 

Would there be interest in getting that setup @halfbyte ? Seems like there are currently a number of out of date dependencies (excluding packages that are intentionally behind like `ember-cli`).

**Comment by halfbyte** [comment]
@mpminardi Sorry for being so absent, it's all a bit embarassing but my time was very limited in the past few months.

As the cofounder of Depfu I am not super keep on introducing Dependabot here, but I realise that it's pretty much standard in the Ember community, so I won't vote against that. I believe I need help for that but my plan for the next few weeks is anyway to get someone from the adopted core team to, ahem, adopt this and walk through the open todos with me and we can add Dependabot then.

**Comment by halfbyte** [comment]
Done!
